Repository Whist-Team/Whist-Core, pull requests merged in 2022-07, with the labels that each got.

#213 FIX: next trick after maximum
  tests/whist_core/game/test_hand.py
  whist_core/game/errors.py
  whist_core/game/hand.py
Labels: bug

#224 Update all workflows
  .github/workflows/lint.yml
  .github/workflows/pylint.yml
  .github/workflows/python-ci.yml
  .github/workflows/python-publish.yml
  .github/workflows/stale.yml
  whist_core/cards/card_container.py
  whist_core/session/matcher.py
Labels: ci

#226 UPDATE: use global action
  .github/workflows/python-ci.yml
Labels: test, github_actions, ci

#225 UPDATE: extract score calculator
  tests/whist_core/game/test_play_order.py
  tests/whist_core/scoring/test_score_calculator.py
  whist_core/game/game.py
  whist_core/game/play_order.py
  whist_core/scoring/score_calculator.py
Labels: enhancement

#227 Fix/negative rating
  tests/whist_core/user/test_player.py
  whist_core/error/player_error.py
  whist_core/user/player.py
Labels: bug
