Repository Whist-Team/Whist-Core, pull requests merged in 2022-01, with the labels that each got.

#140 UPDATE: disable fail fast test workflow
  .github/workflows/python-app.yml
Labels: github_actions

#141 FIX: player ratings test
  tests/whist/core/team_base_test_case.py
Labels: bug

#142 FEATURE: hand has a getter for current trick
  tests/whist/core/game/test_hand.py
  whist/core/game/hand.py
Labels: enhancement

#137 PlayerAtTable overhaul
  tests/whist/core/game/test_hand.py
  tests/whist/core/game/test_play_order.py
  tests/whist/core/game/test_trick.py
  tests/whist/core/player_table_base_test_case.py
  whist/core/game/hand.py
  whist/core/game/play_order.py
Labels: enhancement

#143 doc/contributing
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: documentation

#138 FEATURE: getter for current stack of trick
  tests/whist/core/cards/test_stack.py
  tests/whist/core/game/test_trick.py
  whist/core/cards/stack.py
  whist/core/game/trick.py
Labels: enhancement

#146 FIX: stack test
  tests/whist/core/game/test_trick.py
Labels: bug

#148 FIX: only hand once
  tests/whist/core/game/test_hand.py
  whist/core/error/hand_error.py
  whist/core/game/hand.py
Labels: bug

#154 Refactor card classes to be pydantic
  .github/workflows/pylint.yml
  tests/whist/core/cards/test_card.py
  tests/whist/core/cards/test_card_container.py
  tests/whist/core/cards/test_deck.py
  tests/whist/core/cards/test_hand.py
  tests/whist/core/cards/test_stack.py
  tests/whist/core/game/test_hand.py
  tests/whist/core/game/test_legal_checker.py
  tests/whist/core/game/test_trick.py
  tests/whist/core/player_table_base_test_case.py
  whist/core/cards/card.py
  whist/core/cards/card_container.py
  whist/core/cards/deck.py
  whist/core/cards/hand.py
  whist/core/cards/stack.py
  whist/core/game/hand.py
  whist/core/game/legal_checker.py
  whist/core/game/play_order.py
  whist/core/game/player_at_table.py
  whist/core/game/trick.py
Labels: enhancement

#156 fix trump selection
  tests/whist/core/game/test_hand.py
  whist/core/game/hand.py
Labels: bug

#158 UPDATE: make Trick and PlayerAtTable BaseModel
  tests/whist/core/game/test_hand.py
  tests/whist/core/player_table_base_test_case.py
  whist/core/game/hand.py
  whist/core/game/play_order.py
  whist/core/game/player_at_table.py
  whist/core/game/trick.py
Labels: enhancement

#160 REWORK: players to team distribution
  tests/whist/core/session/test_matcher.py
  tests/whist/core/session/test_table.py
  whist/core/game/rubber.py
  whist/core/session/matcher.py
  whist/core/session/table.py
Labels: enhancement

#162 FIX: not enough players could be sent to matcher
  tests/whist/core/session/test_matcher.py
  tests/whist/core/session/test_table.py
  whist/core/error/matcher_error.py
  whist/core/session/matcher.py
  whist/core/session/table.py
Labels: bug

#165 FIX: enum class in dictionary
  tests/whist/core/cards/test_card.py
  whist/core/cards/card.py
Labels: bug
